// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.3
// source: plugin.proto

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WidgetPlugin_FetchData_FullMethodName = "/dashboard.plugin.WidgetPlugin/FetchData"
	WidgetPlugin_Render_FullMethodName    = "/dashboard.plugin.WidgetPlugin/Render"
)

// WidgetPluginClient is the client API for WidgetPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WidgetPluginClient interface {
	FetchData(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error)
}

type widgetPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewWidgetPluginClient(cc grpc.ClientConnInterface) WidgetPluginClient {
	return &widgetPluginClient{cc}
}

func (c *widgetPluginClient) FetchData(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, WidgetPlugin_FetchData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetPluginClient) Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderResponse)
	err := c.cc.Invoke(ctx, WidgetPlugin_Render_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WidgetPluginServer is the server API for WidgetPlugin service.
// All implementations must embed UnimplementedWidgetPluginServer
// for forward compatibility.
type WidgetPluginServer interface {
	FetchData(context.Context, *FetchRequest) (*FetchResponse, error)
	Render(context.Context, *RenderRequest) (*RenderResponse, error)
	mustEmbedUnimplementedWidgetPluginServer()
}

// UnimplementedWidgetPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWidgetPluginServer struct{}

func (UnimplementedWidgetPluginServer) FetchData(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchData not implemented")
}
func (UnimplementedWidgetPluginServer) Render(context.Context, *RenderRequest) (*RenderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Render not implemented")
}
func (UnimplementedWidgetPluginServer) mustEmbedUnimplementedWidgetPluginServer() {}
func (UnimplementedWidgetPluginServer) testEmbeddedByValue()                      {}

// UnsafeWidgetPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WidgetPluginServer will
// result in compilation errors.
type UnsafeWidgetPluginServer interface {
	mustEmbedUnimplementedWidgetPluginServer()
}

func RegisterWidgetPluginServer(s grpc.ServiceRegistrar, srv WidgetPluginServer) {
	// If the following call panics, it indicates UnimplementedWidgetPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WidgetPlugin_ServiceDesc, srv)
}

func _WidgetPlugin_FetchData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetPluginServer).FetchData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WidgetPlugin_FetchData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetPluginServer).FetchData(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetPlugin_Render_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetPluginServer).Render(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WidgetPlugin_Render_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetPluginServer).Render(ctx, req.(*RenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WidgetPlugin_ServiceDesc is the grpc.ServiceDesc for WidgetPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WidgetPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dashboard.plugin.WidgetPlugin",
	HandlerType: (*WidgetPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchData",
			Handler:    _WidgetPlugin_FetchData_Handler,
		},
		{
			MethodName: "Render",
			Handler:    _WidgetPlugin_Render_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
